WITH live_users AS (SELECT id FROM app_user WHERE deleted_yn=0 AND test_yn=0 AND temp_yn=0 AND (phone NOT IN ('01020866510','01035474964','01093277016','01091350157','01043446885','01049664316','01050373300','01066943645','01073740979','01092828753','01035420850','01051415705','01091622508','01000000000') OR phone IS NULL)),
target_users AS (SELECT DISTINCT c.user_id FROM car c JOIN car_model_target cmt ON cmt.id=c.model_id WHERE c.deleted_yn=0 AND cmt.is_target=1),
washed_reservations AS (SELECT r.id, r.user_id, r.reservation_datetime FROM reservation r JOIN live_users lu ON lu.id=r.user_id JOIN target_users tu ON tu.user_id=r.user_id WHERE r.status IN ('WASHED','REPORT_SENT') AND r.deleted_yn=0 AND DATE_ADD(r.reservation_datetime, INTERVAL 9 HOUR)>=DATE_SUB(DATE_ADD(UTC_TIMESTAMP(), INTERVAL 9 HOUR), INTERVAL 12 MONTH)),
us_base AS (SELECT us.id AS user_service_id, us.reservation_id, us.payment_id, us.product_id, us.service_id, s.price AS service_price FROM user_service us JOIN washed_reservations wr ON wr.id=us.reservation_id JOIN service s ON s.id=us.service_id WHERE us.deleted_yn=0 AND us.paid_yn=1 AND us.used_yn=1),
uo_base AS (SELECT uo.id AS user_option_id, uo.reservation_id, uo.payment_id, uo.option_id, o.price AS option_price FROM user_option uo JOIN washed_reservations wr ON wr.id=uo.reservation_id JOIN options o ON o.id=uo.option_id WHERE uo.deleted_yn=0 AND uo.paid_yn=1 AND uo.used_yn=1),
us_counts AS (SELECT payment_id, product_id, COUNT(*) AS user_service_count FROM us_base WHERE payment_id IS NOT NULL AND product_id IS NOT NULL GROUP BY payment_id, product_id),
uo_counts AS (SELECT payment_id, option_id, COUNT(*) AS user_option_count FROM uo_base WHERE payment_id IS NOT NULL GROUP BY payment_id, option_id),
price_items AS (SELECT p.id AS payment_id, jt.item_type, jt.item_id, jt.item_price, jt.item_original_price FROM payment p LEFT JOIN JSON_TABLE(p.metadata,'$.prices[*]' COLUMNS(item_type VARCHAR(32) PATH '$.type', item_id INT PATH '$.id', item_price INT PATH '$.price', item_original_price INT PATH '$.originalPrice')) jt ON TRUE WHERE p.deleted_yn=false AND p.status IN ('PAID','PARTIAL_CANCELED')),
payment_points AS (SELECT p.id AS payment_id, COALESCE(pm.point_amount, CAST(JSON_UNQUOTE(JSON_EXTRACT(p.metadata,'$.point')) AS SIGNED), 0) AS point_amount FROM payment p LEFT JOIN (SELECT payment_id, SUM(amount) AS point_amount FROM payment_medium WHERE medium='POINT' GROUP BY payment_id) pm ON pm.payment_id=p.id WHERE p.deleted_yn=false AND p.status IN ('PAID','PARTIAL_CANCELED')),
payment_cancels AS (SELECT p.id AS payment_id, p.cancel_amount FROM payment p WHERE p.deleted_yn=false AND p.status='PARTIAL_CANCELED' AND p.cancel_amount>0),
service_ticket_items AS (SELECT us.user_service_id AS item_ref_id, us.reservation_id, us.payment_id, IF(us.payment_id IS NULL,0,COALESCE(pi.item_price/NULLIF(uc.user_service_count,0),us.service_price)) AS base_price, COALESCE(pi.item_original_price/NULLIF(uc.user_service_count,0),us.service_price) AS original_price FROM us_base us LEFT JOIN us_counts uc ON uc.payment_id=us.payment_id AND uc.product_id=us.product_id LEFT JOIN price_items pi ON pi.payment_id=us.payment_id AND pi.item_type='PRODUCT' AND pi.item_id=us.product_id),
option_items AS (SELECT uo.user_option_id AS item_ref_id, uo.reservation_id, uo.payment_id, IF(uo.payment_id IS NULL,0,COALESCE(pi.item_price/NULLIF(oc.user_option_count,0),uo.option_price)) AS base_price, COALESCE(pi.item_original_price/NULLIF(oc.user_option_count,0),uo.option_price) AS original_price FROM uo_base uo LEFT JOIN uo_counts oc ON oc.payment_id=uo.payment_id AND oc.option_id=uo.option_id LEFT JOIN price_items pi ON pi.payment_id=uo.payment_id AND pi.item_type='OPTION' AND pi.item_id=uo.option_id),
service_change_items AS (SELECT us.id AS item_ref_id, us.reservation_id, p.id AS payment_id, ci.price AS base_price, ci.price AS original_price FROM cart_item ci JOIN cart c ON c.id=ci.cart_id JOIN payment p ON p.cart_id=c.id JOIN user_service us ON us.id=ci.user_service_id JOIN washed_reservations wr ON wr.id=us.reservation_id WHERE ci.type IN ('SERVICE_UPGRADE','SERVICE_DOWNGRADE') AND (ci.deleted_yn=false OR ci.deleted_yn=0) AND p.deleted_yn=false AND p.status IN ('PAID','PARTIAL_CANCELED')),
all_items AS (SELECT item_ref_id, reservation_id, payment_id, base_price, original_price FROM service_ticket_items UNION ALL SELECT item_ref_id, reservation_id, payment_id, base_price, original_price FROM option_items UNION ALL SELECT item_ref_id, reservation_id, payment_id, base_price, original_price FROM service_change_items),
payment_totals AS (SELECT payment_id, SUM(CASE WHEN original_price>0 THEN original_price ELSE 0 END) AS total_positive_original_price FROM all_items WHERE payment_id IS NOT NULL GROUP BY payment_id),
items_with_point AS (SELECT ai.*, COALESCE(pp.point_amount,0) AS point_amount, COALESCE(pt.total_positive_original_price,0) AS total_positive_original_price, IF(ai.original_price>0 AND COALESCE(pt.total_positive_original_price,0)>0, ROUND(COALESCE(pp.point_amount,0)*ai.original_price/pt.total_positive_original_price),0) AS point_alloc, IF(ai.original_price>0 AND COALESCE(pt.total_positive_original_price,0)>0, ROUND(COALESCE(pc.cancel_amount,0)*ai.original_price/pt.total_positive_original_price),0) AS cancel_alloc FROM all_items ai LEFT JOIN payment_points pp ON pp.payment_id=ai.payment_id LEFT JOIN payment_totals pt ON pt.payment_id=ai.payment_id LEFT JOIN payment_cancels pc ON pc.payment_id=ai.payment_id),
reservation_revenue AS (SELECT reservation_id, SUM(base_price-point_alloc-cancel_alloc) AS sale_total FROM items_with_point GROUP BY reservation_id),
onsite_revenue AS (SELECT oc.reservation_id, SUM(COALESCE(gi.gross,0)+COALESCE(aj.adj,0)) AS onsite_total FROM reservation_onsite_collection oc JOIN washed_reservations wr ON wr.id=oc.reservation_id LEFT JOIN (SELECT collection_id, SUM(amount_snapshot) AS gross FROM reservation_onsite_collection_item WHERE canceled_at IS NULL GROUP BY collection_id) gi ON gi.collection_id=oc.id LEFT JOIN (SELECT i.collection_id, SUM(a.amount) AS adj FROM reservation_onsite_collection_item_adjustment a JOIN reservation_onsite_collection_item i ON i.id=a.collection_item_id AND i.canceled_at IS NULL GROUP BY i.collection_id) aj ON aj.collection_id=oc.id WHERE oc.status<>'CANCELED' GROUP BY oc.reservation_id)
SELECT CAST(DATE_FORMAT(DATE_ADD(wr.reservation_datetime, INTERVAL 9 HOUR),'%Y-%m-01') AS DATE) AS time, ROUND(SUM(COALESCE(rr.sale_total,0)+COALESCE(orv.onsite_total,0))) AS revenue_total_target
FROM washed_reservations wr LEFT JOIN reservation_revenue rr ON rr.reservation_id=wr.id LEFT JOIN onsite_revenue orv ON orv.reservation_id=wr.id
GROUP BY time ORDER BY time
